on: [push, pull_request]
name: Test
jobs:
  test:
    env:
      GOPROXY: https://proxy.golang.org
      GO111MODULE: on
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go
        with:
          go-version: 1.15

      - name: Install Mage
        run: go get github.com/magefile/mage

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Test
        run: |
          mage -v test
          mage -v check;
